### ISSUE TITLE
又怕云插件好像不支持PHP8.1

### ISSUE THREAD

**Issue by ylwzbk** [sy-records/upyun-uss-wordpress#10]
WordPress6.2版本
PHP版本8.1
使用数据库替换功能时Warning: Undefined variable $old_url in /www/wwwroot/域名/wp-content/plugins/uss-upyun/upyun-uss-wordpress.php on line 466

Warning: Undefined variable $new_url in /www/wwwroot/域名/wp-content/plugins/uss-upyun/upyun-uss-wordpress.php on line 466

Warning: Undefined variable $old_url in /www/wwwroot/域名/wp-content/plugins/uss-upyun/upyun-uss-wordpress.php on line 470

Warning: Undefined variable $new_url in /www/wwwroot/域名/wp-content/plugins/uss-upyun/upyun-uss-wordpress.php on line 470

**Comment by sy-records** [comment]
你没填内容就点了替换吧？

**Comment by ylwzbk** [comment]
> 
没有就是填了内容点了替换就这样

**Comment by ylwzbk** [comment]
> 你没填内容就点了替换吧？

没有就是填了内容点了替换就这样
