### ISSUE TITLE
插件的url前缀无法保留

### ISSUE THREAD

**Issue by ylwzbk** [sy-records/upyun-uss-wordpress#11]
安装教程的步骤来添加的 
本地文件夹设置为了：wp-content/uploads
URL前缀：设置为了：https://域名/wp-content/uploads
但点击保存更改了之后URL前缀显示只有：https://域名

WordPress6.2版本
php8.1版本

**Comment by ylwzbk** [comment]
离谱了 我没事多点了好几次 居然可以了

**Comment by sy-records** [comment]
linux还是Windows？什么环境

**Comment by ylwzbk** [comment]
> linux还是Windows？什么环境

linux环境 宝塔面板下搞得
