### ISSUE TITLE
关于图片水印问题

### ISSUE THREAD

**Issue by 380480425** [sy-records/upyun-uss-wordpress#3]
通过编辑器上传的图片可以正常添加水印。
而如果通过其它手段保存网页中的图片到云端，是没有水印的，这个问题在其它云端插件中，是没有的。希望能增强，谢谢！

**Comment by sy-records** [comment]
我插件没有水印功能

**Comment by sy-records** [comment]
应该是插件优先级的问题，修改第三个参数的值试试吧。

https://github.com/sy-records/upyun-uss-wordpress/blob/5a6f725d86e30b6c8cc6f19dade3d47723fb85fa/upyun-uss-wordpress.php#L168

https://github.com/sy-records/upyun-uss-wordpress/blob/5a6f725d86e30b6c8cc6f19dade3d47723fb85fa/upyun-uss-wordpress.php#L222

**Comment by sy-records** [comment]
> 通过其它手段保存网页中的图片到云端，是没有水印的，这个问题在其它云端插件中，是没有的。

这不是水印插件的问题吗？和存储有什么关系？应该是水印插件未处理不在媒体库上传的图片
