### ISSUE TITLE
上传图片被覆盖

### ISSUE THREAD

**Issue by SunSi12138** [sy-records/upyun-uss-wordpress#5]
使用版本1.2.4
wordpress版本5.8

wordpress 编辑器中粘贴使用截图截取的新图片（包括使用windows自带截图、qq截图）上传时，默认使用的是image.png，并且会覆盖原有图片上传
![image](https://user-images.githubusercontent.com/54728594/131384776-b7a858ca-b469-4744-8315-dfa81f9061ef.png)
严重时会导致图片丢失

建议增加重命名功能，用uuid重命名或者其他自定义命名规则
还有检测是否已经存在同名文件防止上传覆盖的问题出现

**Comment by sy-records** [comment]
插件有提供自动重命名文件的功能，你配置了吗？

媒体库上传图片正常吗？
